### ISSUE TITLE
Error in app.py

### ISSUE THREAD

**Issue by adarshkarne** [adarshkarne/WebApp#3]
Error: (.venv) @adarshkarne ➜ /workspaces/WebApp (main) $ /workspaces/WebApp/.venv/bin/python /workspaces/WebApp/WebApp/D3js_Flask/app.py
Traceback (most recent call last):
  File "/workspaces/WebApp/WebApp/D3js_Flask/app.py", line 13, in <module>
    def main():
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/scaffold.py", line 364, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/scaffold.py", line 44, in wrapper_func
    return f(self, *args, **kwargs)
  File "/workspaces/WebApp/.venv/lib/python3.10/site-packages/flask/sansio/app.py", line 659, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: main

Commit Id: "e2637ab".

**Comment by psurkanti** [comment]
issue resolved

**Comment by adarshkarne** [comment]
resolved
